### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SSUzunov19** [justitsi/js-belote#17]
**Describe the bug**
Your starting game page isn't working

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Create Room'
3. Then show you your game room code and type your game name
4. When you type a name, you can see that the button remains disabled and you cannot press it to continue and make a game

**Screenshots**
https://prnt.sc/X7AXQxdxDwfS

**Comment by justitsi** [comment]
Thanks for letting me know - this seems to be a network issue rather than an application server problem.

I've looked at the logs (send me an email on hristo@belchev.tk for a copy) and there appears to be no sign of the server crashing. 

Working to resolve the networking problem now 🔧
